<?php

namespace CodeShopping\Http\Filters;

use Illuminate\Database\Query\Builder;
use Mnabialek\LaravelEloquentFilter\Filters\SimpleQueryFilter;

class ProductInputFilter extends SimpleQueryFilter
{
    protected $simpleFilters = ['search']; // nome do produto

    protected $simpleSorts = ['id', 'name', 'created_at'];

    protected function applySearch($value){
        $this->query->where('name', 'LIKE', "%$value%");
    }

    /**
     * @param Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function apply($query)
    {
        $query = $query
            ->select('product_inputs.*')
            ->join('products', 'product_id', '=', 'product_inputs.product_id');
        return parent::apply($query); // TODO: Change the autogenerated stub
    }
}